version: '3.9'

networks:
  film-net:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./build/schema/:/docker-entrypoint-initdb.d/
    ports:
      - "$DB_PORT:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
    - film-net
  
volumes:
  pg-data: