// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  model

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Actor ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Actor ) UnmarshalJSON([]byte) error { return nil }
func ( Actor ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Actor ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Actor *Actor

func ( FilmObj ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FilmObj ) UnmarshalJSON([]byte) error { return nil }
func ( FilmObj ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FilmObj ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FilmObj *FilmObj

func ( ResponseActor ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ResponseActor ) UnmarshalJSON([]byte) error { return nil }
func ( ResponseActor ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ResponseActor ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ResponseActor *ResponseActor
